language: node_js
node_js:
  - v4
  - v6
  - v8
notifications:
  email:
    - XChen@walmartlabs.com
    - ananavati@walmartlabs.com
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; npm --version; fi
  - npm install -g xclap-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
